export const userDataFriendship = [
  {
    id: 1,
    image: require('../assets/first-girl.png'),
    name: 'Sandra Gómez',
    age: 21,
    country: 'Perú',
    city: 'Surco',
    interests: ['Viajar', 'Leer', 'Amistad', 'Salir de fiesta', 'Pasarlo bien'],
    genderIdentity: '',
  },
  {
    id: 2,
    image: require('../assets/second-girl.png'),
    name: 'Beatriz',
    age: 22,
    country: 'Perú',
    city: 'Lima',
    interests: ['Viajar', 'Leer', 'Salir de fiesta'],
    genderIdentity: ['Femme'],
  },
  {
    id: 3,
    image: require('../assets/third-girl.png'),
    name: 'Alondra',
    age: 27,
    country: 'Perú',
    city: 'San Isidro',
    interests: ['Viajar', 'Leer', 'Pasarlo bien'],
    genderIdentity: ['Femme'],
  },
];

export const userDataDates = [
  {
    id: 1,
    image: require('../assets/second-girl.png'),
    name: 'Beatriz',
    age: 22,
    country: 'Perú',
    city: 'Lima',
    interests: ['Viajar', 'Leer', 'Salir de fiesta'],
    genderIdentity: ['Femme'],
  },
  {
    id: 2,
    image: require('../assets/third-girl.png'),
    name: 'Alondra',
    age: 27,
    country: 'Perú',
    city: 'San Isidro',
    interests: ['Viajar', 'Leer', 'Pasarlo bien'],
    genderIdentity: ['Femme'],
  },
  {
    id: 3,
    image: require('../assets/first-girl.png'),
    name: 'Sandra Gómez',
    age: 21,
    country: 'Perú',
    city: 'Surco',
    interests: ['Viajar', 'Leer', 'Amistad', 'Salir de fiesta', 'Pasarlo bien'],
    genderIdentity: '',
  },
];

export const userDataRelationship = [
  {
    id: 1,
    image: require('../assets/third-girl.png'),
    name: 'Alondra',
    age: 27,
    country: 'Perú',
    city: 'San Isidro',
    interests: ['Viajar', 'Leer', 'Pasarlo bien'],
    genderIdentity: ['Femme'],
  },
  {
    id: 2,
    image: require('../assets/first-girl.png'),
    name: 'Sandra Gómez',
    age: 21,
    country: 'Perú',
    city: 'Surco',
    interests: ['Viajar', 'Leer', 'Amistad', 'Salir de fiesta', 'Pasarlo bien'],
    genderIdentity: '',
  },
  {
    id: 3,
    image: require('../assets/second-girl.png'),
    name: 'Beatriz',
    age: 22,
    country: 'Perú',
    city: 'Lima',
    interests: ['Viajar', 'Leer', 'Salir de fiesta'],
    meConsidero: ['Femme'],
  },
];
